---
title: signnet - Methods to Analyse Signed Networks
format:
  html:
    embed-resources: true
  gfm: default
---

## Description

<!-- - Provide a brief and clear description of the method, its purpose, and what it aims to achieve. Add a link to a related paper from social science domain and show how your method can be applied to solve that research question.   -->

Methods for the analysis of signed networks. This includes
several measures for structural balance as introduced by Cartwright
and Harary (1956) [<doi:10.1037/h0046049>](https://doi.org/10.1037/h0046049), blockmodeling algorithms
from Doreian (2008) [<doi:10.1016/j.socnet.2008.03.005>](https://doi.org/10.1016/j.socnet.2008.03.005), various
centrality indices, and projections of signed two-mode networks
introduced by Schoch (2020) [<doi:10.1080/0022250X.2019.1711376>](https://doi.org/10.1080/0022250X.2019.1711376).

## Keywords

<!-- EDITME -->

* Network Analysis 
* Signed Networks
* Blockmodelling

## Social Science Usecase(s)

Signet networks offer valuable insights into the dynamics of relationships in social science. By modeling networks with positive and negative ties, such as trust and distrust or alliance and rivalry, researchers can explore the nuanced interplay of influence and group structures within societies. Signed centrality helps identify key actors who exert positive influence or act as polarizing figures, while blockmodeling reveals cohesive subgroups and structural roles, such as brokers or marginalized factions, within the network. These tools are instrumental in studying phenomena like political polarization, social cohesion, and conflict resolution, offering a framework for analyzing both cooperative and antagonistic interactions in complex social systems.


## Repository structure

This repository follows [the standard structure of an R package](https://cran.r-project.org/doc/FAQ/R-exts.html#Package-structure).

## Environment Setup

With R installed:

```r
install.packages("signnet")
```

<!-- ## Hardware Requirements (Optional) -->
<!-- - The hardware requirements may be needed in specific cases when a method is known to require more memory/compute power.  -->
<!-- - The method need to be executed on a specific architecture (GPUs, Hadoop cluster etc.) -->


## Input Data 

<!-- - The input data has to be a Digital Behavioral Data (DBD) Dataset -->
<!-- - You can provide link to a public DBD dataset. GESIS DBD datasets (https://www.gesis.org/en/institute/digital-behavioral-data) -->

<!-- This is an example -->

`signnet` accepts network data in `igraph` format. The sign information is stored in a node attribute `sign`.

## Sample Input and Output Data

The package includes two example data sets that can be used to test the methods.

## How to Use

The package comes with a set of vignettes that can be found [here](https://schochastics.github.io/signnet/).

## Contact Details

Maintainer: David Schoch <david@schochastics.net>

Issue Tracker: [https://github.com/schochastics/signnet/issues](https://github.com/schochastics/signnet/issues)

<!-- ## Publication -->
<!-- - Include information on publications or articles related to the method, if applicable. -->

<!-- ## Acknowledgements -->
<!-- - Acknowledgements if any -->

<!-- ## Disclaimer -->
<!-- - Add any disclaimers, legal notices, or usage restrictions for the method, if necessary. -->
