// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// blockCriterion
double blockCriterion(const arma::sp_mat& A, IntegerVector clu, IntegerMatrix sgrp, double alpha);
RcppExport SEXP _signnet_blockCriterion(SEXP ASEXP, SEXP cluSEXP, SEXP sgrpSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type sgrp(sgrpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(blockCriterion(A, clu, sgrp, alpha));
    return rcpp_result_gen;
END_RCPP
}
// blockGreedy
List blockGreedy(const arma::sp_mat& A, IntegerVector clu, IntegerMatrix sgrp, double alpha, int maxiter);
RcppExport SEXP _signnet_blockGreedy(SEXP ASEXP, SEXP cluSEXP, SEXP sgrpSEXP, SEXP alphaSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type sgrp(sgrpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(blockGreedy(A, clu, sgrp, alpha, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// blockAnneal
List blockAnneal(const arma::sp_mat& A, IntegerVector clu, IntegerMatrix sgrp, double alpha, double temp0, double cooling, double temp_min, int iter_per_temp);
RcppExport SEXP _signnet_blockAnneal(SEXP ASEXP, SEXP cluSEXP, SEXP sgrpSEXP, SEXP alphaSEXP, SEXP temp0SEXP, SEXP coolingSEXP, SEXP temp_minSEXP, SEXP iter_per_tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type sgrp(sgrpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type temp0(temp0SEXP);
    Rcpp::traits::input_parameter< double >::type cooling(coolingSEXP);
    Rcpp::traits::input_parameter< double >::type temp_min(temp_minSEXP);
    Rcpp::traits::input_parameter< int >::type iter_per_temp(iter_per_tempSEXP);
    rcpp_result_gen = Rcpp::wrap(blockAnneal(A, clu, sgrp, alpha, temp0, cooling, temp_min, iter_per_temp));
    return rcpp_result_gen;
END_RCPP
}
// cxmatmul
arma::cx_mat cxmatmul(const arma::cx_mat& A, const arma::cx_mat& B);
RcppExport SEXP _signnet_cxmatmul(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cxmatmul(A, B));
    return rcpp_result_gen;
END_RCPP
}
// triadCensusSign1
DoubleVector triadCensusSign1(const arma::sp_mat& A, List adj, int n);
RcppExport SEXP _signnet_triadCensusSign1(SEXP ASEXP, SEXP adjSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(triadCensusSign1(A, adj, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_signnet_blockCriterion", (DL_FUNC) &_signnet_blockCriterion, 4},
    {"_signnet_blockGreedy", (DL_FUNC) &_signnet_blockGreedy, 5},
    {"_signnet_blockAnneal", (DL_FUNC) &_signnet_blockAnneal, 8},
    {"_signnet_cxmatmul", (DL_FUNC) &_signnet_cxmatmul, 2},
    {"_signnet_triadCensusSign1", (DL_FUNC) &_signnet_triadCensusSign1, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_signnet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
