# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arcDist <- function(x, y, r) {
    .Call('_signnet_arcDist', PACKAGE = 'signnet', x, y, r)
}

arcDistMat <- function(X, r) {
    .Call('_signnet_arcDistMat', PACKAGE = 'signnet', X, r)
}

