# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blockCriterion <- function(A, clu, sgrp, alpha) {
    .Call(`_signnet_blockCriterion`, A, clu, sgrp, alpha)
}

blockGreedy <- function(A, clu, sgrp, alpha, maxiter) {
    .Call(`_signnet_blockGreedy`, A, clu, sgrp, alpha, maxiter)
}

blockAnneal <- function(A, clu, sgrp, alpha, temp0, cooling, temp_min, iter_per_temp) {
    .Call(`_signnet_blockAnneal`, A, clu, sgrp, alpha, temp0, cooling, temp_min, iter_per_temp)
}

arcDist <- function(x, y, r) {
    .Call(`_signnet_arcDist`, x, y, r)
}

arcDistMat <- function(X, r) {
    .Call(`_signnet_arcDistMat`, X, r)
}

cxmatmul <- function(A, B) {
    .Call(`_signnet_cxmatmul`, A, B)
}

triadCensusSign <- function(A, n) {
    .Call(`_signnet_triadCensusSign`, A, n)
}

triadCensusSign1 <- function(A, adj, n) {
    .Call(`_signnet_triadCensusSign1`, A, adj, n)
}

